upload:
  video:
    path: ./videos/videos #绝对路径
    image: ./videos/images
  teri-tag:
    image: ./teri-tag/image
    docs: ./teri-tag/docs
  avatar:
    image: ./avatar/image
spring:
  datasource:
    url: jdbc:mysql://109.176.255.210:9929/teriedu?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: test1
    password: passwd@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    enable: false
  servlet:
    multipart:
      max-file-size: 2000MB       # 单个文件的最大大小
      max-request-size: 2000MB   # 单次请求的总大小
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
logging:
  level:
    com.fasterxml.jackson: DEBUG